name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        
    - name: Install dependencies
      run: dotnet restore src/Chronos.P2P.Test
    - name: Build
      run: dotnet build src/Chronos.P2P.Test --configuration Release --no-restore
    - name: Test
      run: dotnet test src/Chronos.P2P.Test --no-restore --verbosity normal
